name: Fetch Visitors Data

on:
  schedule:
    # Run every hour (adjust cron expression as needed)
    - cron: '0 * * * *'

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium schedule

    - name: Run Python script
      run: python fetch_visitors.py

    - name: Commit CSV file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add visitors_data.csv
        git commit -m "Update visitors data"
        git push
